export const PhoneCountryCodes = [
  { code: "+93", country: "af" },
  { code: "+355", country: "al" },
  { code: "+213", country: "dz" },
  { code: "+1", country: "as" },
  { code: "+376", country: "ad" },
  { code: "+244", country: "ao" },
  { code: "+1", country: "ai" },
  { code: "+672", country: "aq" },
  { code: "+1", country: "ag" },
  { code: "+54", country: "ar" },
  { code: "+374", country: "am" },
  { code: "+297", country: "aw" },
  { code: "+61", country: "au" },
  { code: "+43", country: "at" },
  { code: "+994", country: "az" },

  { code: "+1", country: "bs" },
  { code: "+973", country: "bh" },
  { code: "+880", country: "bd" },
  { code: "+1", country: "bb" },
  { code: "+375", country: "by" },
  { code: "+32", country: "be" },
  { code: "+501", country: "bz" },
  { code: "+229", country: "bj" },
  { code: "+1", country: "bm" },
  { code: "+975", country: "bt" },
  { code: "+591", country: "bo" },
  { code: "+387", country: "ba" },
  { code: "+267", country: "bw" },
  { code: "+55", country: "br" },
  { code: "+246", country: "io" },
  { code: "+673", country: "bn" },
  { code: "+359", country: "bg" },
  { code: "+226", country: "bf" },
  { code: "+257", country: "bi" },

  { code: "+855", country: "kh" },
  { code: "+237", country: "cm" },
  { code: "+1", country: "ca" },
  { code: "+238", country: "cv" },
  { code: "+1", country: "ky" },
  { code: "+236", country: "cf" },
  { code: "+235", country: "td" },
  { code: "+56", country: "cl" },
  { code: "+86", country: "cn" },
  { code: "+61", country: "cx" },
  { code: "+61", country: "cc" },
  { code: "+57", country: "co" },
  { code: "+269", country: "km" },
  { code: "+242", country: "cg" },
  { code: "+243", country: "cd" },
  { code: "+682", country: "ck" },
  { code: "+506", country: "cr" },
  { code: "+225", country: "ci" },
  { code: "+385", country: "hr" },
  { code: "+53", country: "cu" },
  { code: "+357", country: "cy" },
  { code: "+420", country: "cz" },

  { code: "+45", country: "dk" },
  { code: "+253", country: "dj" },
  { code: "+1", country: "dm" },
  { code: "+1", country: "do" },

  { code: "+593", country: "ec" },
  { code: "+20", country: "eg" },
  { code: "+503", country: "sv" },
  { code: "+240", country: "gq" },
  { code: "+291", country: "er" },
  { code: "+372", country: "ee" },
  { code: "+251", country: "et" },

  { code: "+500", country: "fk" },
  { code: "+298", country: "fo" },
  { code: "+679", country: "fj" },
  { code: "+358", country: "fi" },
  { code: "+33", country: "fr" },

  { code: "+594", country: "gf" },
  { code: "+689", country: "pf" },
  { code: "+241", country: "ga" },
  { code: "+220", country: "gm" },
  { code: "+995", country: "ge" },
  { code: "+49", country: "de" },
  { code: "+233", country: "gh" },
  { code: "+350", country: "gi" },
  { code: "+30", country: "gr" },
  { code: "+299", country: "gl" },
  { code: "+1", country: "gd" },
  { code: "+590", country: "gp" },
  { code: "+1", country: "gu" },
  { code: "+502", country: "gt" },
  { code: "+224", country: "gn" },
  { code: "+245", country: "gw" },
  { code: "+592", country: "gy" },

  { code: "+509", country: "ht" },
  { code: "+504", country: "hn" },
  { code: "+852", country: "hk" },
  { code: "+36", country: "hu" },

  { code: "+354", country: "is" },
  { code: "+91", country: "in" },
  { code: "+62", country: "id" },
  { code: "+98", country: "ir" },
  { code: "+964", country: "iq" },
  { code: "+353", country: "ie" },
  { code: "+972", country: "il" },
  { code: "+39", country: "it" },

  { code: "+1", country: "jm" },
  { code: "+81", country: "jp" },
  { code: "+962", country: "jo" },

  { code: "+7", country: "kz" },
  { code: "+254", country: "ke" },
  { code: "+686", country: "ki" },
  { code: "+965", country: "kw" },
  { code: "+996", country: "kg" },

  { code: "+856", country: "la" },
  { code: "+371", country: "lv" },
  { code: "+961", country: "lb" },
  { code: "+266", country: "ls" },
  { code: "+231", country: "lr" },
  { code: "+218", country: "ly" },
  { code: "+423", country: "li" },
  { code: "+370", country: "lt" },
  { code: "+352", country: "lu" },

  { code: "+853", country: "mo" },
  { code: "+389", country: "mk" },
  { code: "+261", country: "mg" },
  { code: "+265", country: "mw" },
  { code: "+60", country: "my" },
  { code: "+960", country: "mv" },
  { code: "+223", country: "ml" },
  { code: "+356", country: "mt" },
  { code: "+692", country: "mh" },
  { code: "+596", country: "mq" },
  { code: "+222", country: "mr" },
  { code: "+230", country: "mu" },
  { code: "+262", country: "yt" },
  { code: "+52", country: "mx" },
  { code: "+691", country: "fm" },
  { code: "+373", country: "md" },
  { code: "+377", country: "mc" },
  { code: "+976", country: "mn" },
  { code: "+382", country: "me" },
  { code: "+212", country: "ma" },
  { code: "+258", country: "mz" },

  { code: "+234", country: "ng" },
  { code: "+27", country: "za" },
  { code: "+44", country: "gb" },
  { code: "+1", country: "us" },
];
