const countryCodes = [
  {
    value: "+93",
    label: "+93",
    flag: "🇦🇫",
    country: "Afghanistan",
    iso2: "AF",
  },
  { value: "+355", label: "+355", flag: "🇦🇱", country: "Albania", iso2: "AL" },
  { value: "+213", label: "+213", flag: "🇩🇿", country: "Algeria", iso2: "DZ" },
  {
    value: "+1684",
    label: "+1684",
    flag: "🇦🇸",
    country: "American Samoa",
    iso2: "AS",
  },
  { value: "+376", label: "+376", flag: "🇦🇩", country: "Andorra", iso2: "AD" },
  { value: "+244", label: "+244", flag: "🇦🇴", country: "Angola", iso2: "AO" },
  {
    value: "+1264",
    label: "+1264",
    flag: "🇦🇮",
    country: "Anguilla",
    iso2: "AI",
  },
  {
    value: "+672",
    label: "+672",
    flag: "🇦🇶",
    country: "Antarctica",
    iso2: "AQ",
  },
  {
    value: "+1268",
    label: "+1268",
    flag: "🇦🇬",
    country: "Antigua and Barbuda",
    iso2: "AG",
  },
  { value: "+54", label: "+54", flag: "🇦🇷", country: "Argentina", iso2: "AR" },
  { value: "+374", label: "+374", flag: "🇦🇲", country: "Armenia", iso2: "AM" },
  { value: "+297", label: "+297", flag: "🇦🇼", country: "Aruba", iso2: "AW" },
  { value: "+61", label: "+61", flag: "🇦🇺", country: "Australia", iso2: "AU" },
  { value: "+43", label: "+43", flag: "🇦🇹", country: "Austria", iso2: "AT" },
  {
    value: "+994",
    label: "+994",
    flag: "🇦🇿",
    country: "Azerbaijan",
    iso2: "AZ",
  },
  {
    value: "+1242",
    label: "+1242",
    flag: "🇧🇸",
    country: "Bahamas",
    iso2: "BS",
  },
  { value: "+973", label: "+973", flag: "🇧🇭", country: "Bahrain", iso2: "BH" },
  {
    value: "+880",
    label: "+880",
    flag: "🇧🇩",
    country: "Bangladesh",
    iso2: "BD",
  },
  {
    value: "+1246",
    label: "+1246",
    flag: "🇧🇧",
    country: "Barbados",
    iso2: "BB",
  },
  { value: "+375", label: "+375", flag: "🇧🇾", country: "Belarus", iso2: "BY" },
  { value: "+32", label: "+32", flag: "🇧🇪", country: "Belgium", iso2: "BE" },
  { value: "+501", label: "+501", flag: "🇧🇿", country: "Belize", iso2: "BZ" },
  { value: "+229", label: "+229", flag: "🇧🇯", country: "Benin", iso2: "BJ" },
  {
    value: "+1441",
    label: "+1441",
    flag: "🇧🇲",
    country: "Bermuda",
    iso2: "BM",
  },
  { value: "+975", label: "+975", flag: "🇧🇹", country: "Bhutan", iso2: "BT" },
  { value: "+591", label: "+591", flag: "🇧🇴", country: "Bolivia", iso2: "BO" },
  {
    value: "+387",
    label: "+387",
    flag: "🇧🇦",
    country: "Bosnia and Herzegovina",
    iso2: "BA",
  },
  { value: "+267", label: "+267", flag: "🇧🇼", country: "Botswana", iso2: "BW" },
  { value: "+55", label: "+55", flag: "🇧🇷", country: "Brazil", iso2: "BR" },
  {
    value: "+246",
    label: "+246",
    flag: "🇮🇴",
    country: "British Indian Ocean Territory",
    iso2: "IO",
  },
  { value: "+673", label: "+673", flag: "🇧🇳", country: "Brunei", iso2: "BN" },
  { value: "+359", label: "+359", flag: "🇧🇬", country: "Bulgaria", iso2: "BG" },
  {
    value: "+226",
    label: "+226",
    flag: "🇧🇫",
    country: "Burkina Faso",
    iso2: "BF",
  },
  { value: "+257", label: "+257", flag: "🇧🇮", country: "Burundi", iso2: "BI" },
  { value: "+855", label: "+855", flag: "🇰🇭", country: "Cambodia", iso2: "KH" },
  { value: "+237", label: "+237", flag: "🇨🇲", country: "Cameroon", iso2: "CM" },
  { value: "+1", label: "+1", flag: "🇨🇦", country: "Canada", iso2: "CA" },
  {
    value: "+238",
    label: "+238",
    flag: "🇨🇻",
    country: "Cape Verde",
    iso2: "CV",
  },
  {
    value: "+1345",
    label: "+1345",
    flag: "🇰🇾",
    country: "Cayman Islands",
    iso2: "KY",
  },
  {
    value: "+236",
    label: "+236",
    flag: "🇨🇫",
    country: "Central African Republic",
    iso2: "CF",
  },
  { value: "+235", label: "+235", flag: "🇹🇩", country: "Chad", iso2: "TD" },
  { value: "+56", label: "+56", flag: "🇨🇱", country: "Chile", iso2: "CL" },
  { value: "+86", label: "+86", flag: "🇨🇳", country: "China", iso2: "CN" },
  {
    value: "+61",
    label: "+61",
    flag: "🇨🇽",
    country: "Christmas Island",
    iso2: "CX",
  },
  {
    value: "+61",
    label: "+61",
    flag: "🇨🇨",
    country: "Cocos Islands",
    iso2: "CC",
  },
  { value: "+57", label: "+57", flag: "🇨🇴", country: "Colombia", iso2: "CO" },
  { value: "+269", label: "+269", flag: "🇰🇲", country: "Comoros", iso2: "KM" },
  { value: "+242", label: "+242", flag: "🇨🇬", country: "Congo", iso2: "CG" },
  {
    value: "+243",
    label: "+243",
    flag: "🇨🇩",
    country: "Congo (DRC)",
    iso2: "CD",
  },
  {
    value: "+682",
    label: "+682",
    flag: "🇨🇰",
    country: "Cook Islands",
    iso2: "CK",
  },
  {
    value: "+506",
    label: "+506",
    flag: "🇨🇷",
    country: "Costa Rica",
    iso2: "CR",
  },
  {
    value: "+225",
    label: "+225",
    flag: "🇨🇮",
    country: "Côte d'Ivoire",
    iso2: "CI",
  },
  { value: "+385", label: "+385", flag: "🇭🇷", country: "Croatia", iso2: "HR" },
  { value: "+53", label: "+53", flag: "🇨🇺", country: "Cuba", iso2: "CU" },
  { value: "+599", label: "+599", flag: "🇨🇼", country: "Curaçao", iso2: "CW" },
  { value: "+357", label: "+357", flag: "🇨🇾", country: "Cyprus", iso2: "CY" },
  {
    value: "+420",
    label: "+420",
    flag: "🇨🇿",
    country: "Czech Republic",
    iso2: "CZ",
  },
  { value: "+45", label: "+45", flag: "🇩🇰", country: "Denmark", iso2: "DK" },
  { value: "+253", label: "+253", flag: "🇩🇯", country: "Djibouti", iso2: "DJ" },
  {
    value: "+1767",
    label: "+1767",
    flag: "🇩🇲",
    country: "Dominica",
    iso2: "DM",
  },
  {
    value: "+1809",
    label: "+1809",
    flag: "🇩🇴",
    country: "Dominican Republic",
    iso2: "DO",
  },
  { value: "+593", label: "+593", flag: "🇪🇨", country: "Ecuador", iso2: "EC" },
  { value: "+20", label: "+20", flag: "🇪🇬", country: "Egypt", iso2: "EG" },
  {
    value: "+503",
    label: "+503",
    flag: "🇸🇻",
    country: "El Salvador",
    iso2: "SV",
  },
  {
    value: "+240",
    label: "+240",
    flag: "🇬🇶",
    country: "Equatorial Guinea",
    iso2: "GQ",
  },
  { value: "+291", label: "+291", flag: "🇪🇷", country: "Eritrea", iso2: "ER" },
  { value: "+372", label: "+372", flag: "🇪🇪", country: "Estonia", iso2: "EE" },
  { value: "+268", label: "+268", flag: "🇸🇿", country: "Eswatini", iso2: "SZ" },
  { value: "+251", label: "+251", flag: "🇪🇹", country: "Ethiopia", iso2: "ET" },
  {
    value: "+500",
    label: "+500",
    flag: "🇫🇰",
    country: "Falkland Islands",
    iso2: "FK",
  },
  {
    value: "+298",
    label: "+298",
    flag: "🇫🇴",
    country: "Faroe Islands",
    iso2: "FO",
  },
  { value: "+679", label: "+679", flag: "🇫🇯", country: "Fiji", iso2: "FJ" },
  { value: "+358", label: "+358", flag: "🇫🇮", country: "Finland", iso2: "FI" },
  { value: "+33", label: "+33", flag: "🇫🇷", country: "France", iso2: "FR" },
  {
    value: "+594",
    label: "+594",
    flag: "🇬🇫",
    country: "French Guiana",
    iso2: "GF",
  },
  {
    value: "+689",
    label: "+689",
    flag: "🇵🇫",
    country: "French Polynesia",
    iso2: "PF",
  },
  { value: "+241", label: "+241", flag: "🇬🇦", country: "Gabon", iso2: "GA" },
  { value: "+220", label: "+220", flag: "🇬🇲", country: "Gambia", iso2: "GM" },
  { value: "+995", label: "+995", flag: "🇬🇪", country: "Georgia", iso2: "GE" },
  { value: "+49", label: "+49", flag: "🇩🇪", country: "Germany", iso2: "DE" },
  { value: "+233", label: "+233", flag: "🇬🇭", country: "Ghana", iso2: "GH" },
  {
    value: "+350",
    label: "+350",
    flag: "🇬🇮",
    country: "Gibraltar",
    iso2: "GI",
  },
  { value: "+30", label: "+30", flag: "🇬🇷", country: "Greece", iso2: "GR" },
  {
    value: "+299",
    label: "+299",
    flag: "🇬🇱",
    country: "Greenland",
    iso2: "GL",
  },
  {
    value: "+1473",
    label: "+1473",
    flag: "🇬🇩",
    country: "Grenada",
    iso2: "GD",
  },
  {
    value: "+590",
    label: "+590",
    flag: "🇬🇵",
    country: "Guadeloupe",
    iso2: "GP",
  },
  { value: "+1671", label: "+1671", flag: "🇬🇺", country: "Guam", iso2: "GU" },
  {
    value: "+502",
    label: "+502",
    flag: "🇬🇹",
    country: "Guatemala",
    iso2: "GT",
  },
  { value: "+44", label: "+44", flag: "🇬🇬", country: "Guernsey", iso2: "GG" },
  { value: "+224", label: "+224", flag: "🇬🇳", country: "Guinea", iso2: "GN" },
  {
    value: "+245",
    label: "+245",
    flag: "🇬🇼",
    country: "Guinea-Bissau",
    iso2: "GW",
  },
  { value: "+592", label: "+592", flag: "🇬🇾", country: "Guyana", iso2: "GY" },
  { value: "+509", label: "+509", flag: "🇭🇹", country: "Haiti", iso2: "HT" },
  { value: "+504", label: "+504", flag: "🇭🇳", country: "Honduras", iso2: "HN" },
  {
    value: "+852",
    label: "+852",
    flag: "🇭🇰",
    country: "Hong Kong",
    iso2: "HK",
  },
  { value: "+36", label: "+36", flag: "🇭🇺", country: "Hungary", iso2: "HU" },
  { value: "+354", label: "+354", flag: "🇮🇸", country: "Iceland", iso2: "IS" },
  { value: "+91", label: "+91", flag: "🇮🇳", country: "India", iso2: "IN" },
  { value: "+62", label: "+62", flag: "🇮🇩", country: "Indonesia", iso2: "ID" },
  { value: "+98", label: "+98", flag: "🇮🇷", country: "Iran", iso2: "IR" },
  { value: "+964", label: "+964", flag: "🇮🇶", country: "Iraq", iso2: "IQ" },
  { value: "+353", label: "+353", flag: "🇮🇪", country: "Ireland", iso2: "IE" },
  {
    value: "+44",
    label: "+44",
    flag: "🇮🇲",
    country: "Isle of Man",
    iso2: "IM",
  },
  { value: "+972", label: "+972", flag: "🇮🇱", country: "Israel", iso2: "IL" },
  { value: "+39", label: "+39", flag: "🇮🇹", country: "Italy", iso2: "IT" },
  {
    value: "+1876",
    label: "+1876",
    flag: "🇯🇲",
    country: "Jamaica",
    iso2: "JM",
  },
  { value: "+81", label: "+81", flag: "🇯🇵", country: "Japan", iso2: "JP" },
  { value: "+44", label: "+44", flag: "🇯🇪", country: "Jersey", iso2: "JE" },
  { value: "+962", label: "+962", flag: "🇯🇴", country: "Jordan", iso2: "JO" },
  { value: "+7", label: "+7", flag: "🇰🇿", country: "Kazakhstan", iso2: "KZ" },
  { value: "+254", label: "+254", flag: "🇰🇪", country: "Kenya", iso2: "KE" },
  { value: "+686", label: "+686", flag: "🇰🇮", country: "Kiribati", iso2: "KI" },
  { value: "+383", label: "+383", flag: "🇽🇰", country: "Kosovo", iso2: "XK" },
  { value: "+965", label: "+965", flag: "🇰🇼", country: "Kuwait", iso2: "KW" },
  {
    value: "+996",
    label: "+996",
    flag: "🇰🇬",
    country: "Kyrgyzstan",
    iso2: "KG",
  },
  { value: "+856", label: "+856", flag: "🇱🇦", country: "Laos", iso2: "LA" },
  { value: "+371", label: "+371", flag: "🇱🇻", country: "Latvia", iso2: "LV" },
  { value: "+961", label: "+961", flag: "🇱🇧", country: "Lebanon", iso2: "LB" },
  { value: "+266", label: "+266", flag: "🇱🇸", country: "Lesotho", iso2: "LS" },
  { value: "+231", label: "+231", flag: "🇱🇷", country: "Liberia", iso2: "LR" },
  { value: "+218", label: "+218", flag: "🇱🇾", country: "Libya", iso2: "LY" },
  {
    value: "+423",
    label: "+423",
    flag: "🇱🇮",
    country: "Liechtenstein",
    iso2: "LI",
  },
  {
    value: "+370",
    label: "+370",
    flag: "🇱🇹",
    country: "Lithuania",
    iso2: "LT",
  },
  {
    value: "+352",
    label: "+352",
    flag: "🇱🇺",
    country: "Luxembourg",
    iso2: "LU",
  },
  { value: "+853", label: "+853", flag: "🇲🇴", country: "Macao", iso2: "MO" },
  {
    value: "+389",
    label: "+389",
    flag: "🇲🇰",
    country: "North Macedonia",
    iso2: "MK",
  },
  {
    value: "+261",
    label: "+261",
    flag: "🇲🇬",
    country: "Madagascar",
    iso2: "MG",
  },
  { value: "+265", label: "+265", flag: "🇲🇼", country: "Malawi", iso2: "MW" },
  { value: "+60", label: "+60", flag: "🇲🇾", country: "Malaysia", iso2: "MY" },
  { value: "+960", label: "+960", flag: "🇲🇻", country: "Maldives", iso2: "MV" },
  { value: "+223", label: "+223", flag: "🇲🇱", country: "Mali", iso2: "ML" },
  { value: "+356", label: "+356", flag: "🇲🇹", country: "Malta", iso2: "MT" },
  {
    value: "+692",
    label: "+692",
    flag: "🇲🇭",
    country: "Marshall Islands",
    iso2: "MH",
  },
  {
    value: "+596",
    label: "+596",
    flag: "🇲🇶",
    country: "Martinique",
    iso2: "MQ",
  },
  {
    value: "+222",
    label: "+222",
    flag: "🇲🇷",
    country: "Mauritania",
    iso2: "MR",
  },
  {
    value: "+230",
    label: "+230",
    flag: "🇲🇺",
    country: "Mauritius",
    iso2: "MU",
  },
  { value: "+262", label: "+262", flag: "🇾🇹", country: "Mayotte", iso2: "YT" },
  { value: "+52", label: "+52", flag: "🇲🇽", country: "Mexico", iso2: "MX" },
  {
    value: "+691",
    label: "+691",
    flag: "🇫🇲",
    country: "Micronesia",
    iso2: "FM",
  },
  { value: "+373", label: "+373", flag: "🇲🇩", country: "Moldova", iso2: "MD" },
  { value: "+377", label: "+377", flag: "🇲🇨", country: "Monaco", iso2: "MC" },
  { value: "+976", label: "+976", flag: "🇲🇳", country: "Mongolia", iso2: "MN" },
  {
    value: "+382",
    label: "+382",
    flag: "🇲🇪",
    country: "Montenegro",
    iso2: "ME",
  },
  {
    value: "+1664",
    label: "+1664",
    flag: "🇲🇸",
    country: "Montserrat",
    iso2: "MS",
  },
  { value: "+212", label: "+212", flag: "🇲🇦", country: "Morocco", iso2: "MA" },
  {
    value: "+258",
    label: "+258",
    flag: "🇲🇿",
    country: "Mozambique",
    iso2: "MZ",
  },
  { value: "+95", label: "+95", flag: "🇲🇲", country: "Myanmar", iso2: "MM" },
  { value: "+264", label: "+264", flag: "🇳🇦", country: "Namibia", iso2: "NA" },
  { value: "+674", label: "+674", flag: "🇳🇷", country: "Nauru", iso2: "NR" },
  { value: "+977", label: "+977", flag: "🇳🇵", country: "Nepal", iso2: "NP" },
  {
    value: "+31",
    label: "+31",
    flag: "🇳🇱",
    country: "Netherlands",
    iso2: "NL",
  },
  {
    value: "+687",
    label: "+687",
    flag: "🇳🇨",
    country: "New Caledonia",
    iso2: "NC",
  },
  {
    value: "+64",
    label: "+64",
    flag: "🇳🇿",
    country: "New Zealand",
    iso2: "NZ",
  },
  {
    value: "+505",
    label: "+505",
    flag: "🇳🇮",
    country: "Nicaragua",
    iso2: "NI",
  },
  { value: "+227", label: "+227", flag: "🇳🇪", country: "Niger", iso2: "NE" },
  { value: "+234", label: "+234", flag: "🇳🇬", country: "Nigeria", iso2: "NG" },
  { value: "+683", label: "+683", flag: "🇳🇺", country: "Niue", iso2: "NU" },
  {
    value: "+672",
    label: "+672",
    flag: "🇳🇫",
    country: "Norfolk Island",
    iso2: "NF",
  },
  {
    value: "+850",
    label: "+850",
    flag: "🇰🇵",
    country: "North Korea",
    iso2: "KP",
  },
  {
    value: "+1670",
    label: "+1670",
    flag: "🇲🇵",
    country: "Northern Mariana Islands",
    iso2: "MP",
  },
  { value: "+47", label: "+47", flag: "🇳🇴", country: "Norway", iso2: "NO" },
  { value: "+968", label: "+968", flag: "🇴🇲", country: "Oman", iso2: "OM" },
  { value: "+92", label: "+92", flag: "🇵🇰", country: "Pakistan", iso2: "PK" },
  { value: "+680", label: "+680", flag: "🇵🇼", country: "Palau", iso2: "PW" },
  {
    value: "+970",
    label: "+970",
    flag: "🇵🇸",
    country: "Palestine",
    iso2: "PS",
  },
  { value: "+507", label: "+507", flag: "🇵🇦", country: "Panama", iso2: "PA" },
  {
    value: "+675",
    label: "+675",
    flag: "🇵🇬",
    country: "Papua New Guinea",
    iso2: "PG",
  },
  { value: "+595", label: "+595", flag: "🇵🇾", country: "Paraguay", iso2: "PY" },
  { value: "+51", label: "+51", flag: "🇵🇪", country: "Peru", iso2: "PE" },
  {
    value: "+63",
    label: "+63",
    flag: "🇵🇭",
    country: "Philippines",
    iso2: "PH",
  },
  { value: "+48", label: "+48", flag: "🇵🇱", country: "Poland", iso2: "PL" },
  { value: "+351", label: "+351", flag: "🇵🇹", country: "Portugal", iso2: "PT" },
  {
    value: "+1787",
    label: "+1787",
    flag: "🇵🇷",
    country: "Puerto Rico",
    iso2: "PR",
  },
  { value: "+974", label: "+974", flag: "🇶🇦", country: "Qatar", iso2: "QA" },
  { value: "+262", label: "+262", flag: "🇷🇪", country: "Réunion", iso2: "RE" },
  { value: "+40", label: "+40", flag: "🇷🇴", country: "Romania", iso2: "RO" },
  { value: "+7", label: "+7", flag: "🇷🇺", country: "Russia", iso2: "RU" },
  { value: "+250", label: "+250", flag: "🇷🇼", country: "Rwanda", iso2: "RW" },
  {
    value: "+590",
    label: "+590",
    flag: "🇧🇱",
    country: "Saint Barthélemy",
    iso2: "BL",
  },
  {
    value: "+290",
    label: "+290",
    flag: "🇸🇭",
    country: "Saint Helena",
    iso2: "SH",
  },
  {
    value: "+1869",
    label: "+1869",
    flag: "🇰🇳",
    country: "Saint Kitts and Nevis",
    iso2: "KN",
  },
  {
    value: "+1758",
    label: "+1758",
    flag: "🇱🇨",
    country: "Saint Lucia",
    iso2: "LC",
  },
  {
    value: "+590",
    label: "+590",
    flag: "🇲🇫",
    country: "Saint Martin",
    iso2: "MF",
  },
  {
    value: "+508",
    label: "+508",
    flag: "🇵🇲",
    country: "Saint Pierre and Miquelon",
    iso2: "PM",
  },
  {
    value: "+1784",
    label: "+1784",
    flag: "🇻🇨",
    country: "Saint Vincent and the Grenadines",
    iso2: "VC",
  },
  { value: "+685", label: "+685", flag: "🇼🇸", country: "Samoa", iso2: "WS" },
  {
    value: "+378",
    label: "+378",
    flag: "🇸🇲",
    country: "San Marino",
    iso2: "SM",
  },
  {
    value: "+239",
    label: "+239",
    flag: "🇸🇹",
    country: "São Tomé and Príncipe",
    iso2: "ST",
  },
  {
    value: "+966",
    label: "+966",
    flag: "🇸🇦",
    country: "Saudi Arabia",
    iso2: "SA",
  },
  { value: "+221", label: "+221", flag: "🇸🇳", country: "Senegal", iso2: "SN" },
  { value: "+381", label: "+381", flag: "🇷🇸", country: "Serbia", iso2: "RS" },
  {
    value: "+248",
    label: "+248",
    flag: "🇸🇨",
    country: "Seychelles",
    iso2: "SC",
  },
  {
    value: "+232",
    label: "+232",
    flag: "🇸🇱",
    country: "Sierra Leone",
    iso2: "SL",
  },
  { value: "+65", label: "+65", flag: "🇸🇬", country: "Singapore", iso2: "SG" },
  {
    value: "+1721",
    label: "+1721",
    flag: "🇸🇽",
    country: "Sint Maarten",
    iso2: "SX",
  },
  { value: "+421", label: "+421", flag: "🇸🇰", country: "Slovakia", iso2: "SK" },
  { value: "+386", label: "+386", flag: "🇸🇮", country: "Slovenia", iso2: "SI" },
  {
    value: "+677",
    label: "+677",
    flag: "🇸🇧",
    country: "Solomon Islands",
    iso2: "SB",
  },
  { value: "+252", label: "+252", flag: "🇸🇴", country: "Somalia", iso2: "SO" },
  {
    value: "+27",
    label: "+27",
    flag: "🇿🇦",
    country: "South Africa",
    iso2: "ZA",
  },
  {
    value: "+82",
    label: "+82",
    flag: "🇰🇷",
    country: "South Korea",
    iso2: "KR",
  },
  {
    value: "+211",
    label: "+211",
    flag: "🇸🇸",
    country: "South Sudan",
    iso2: "SS",
  },
  { value: "+34", label: "+34", flag: "🇪🇸", country: "Spain", iso2: "ES" },
  { value: "+94", label: "+94", flag: "🇱🇰", country: "Sri Lanka", iso2: "LK" },
  { value: "+249", label: "+249", flag: "🇸🇩", country: "Sudan", iso2: "SD" },
  { value: "+597", label: "+597", flag: "🇸🇷", country: "Suriname", iso2: "SR" },
  {
    value: "+47",
    label: "+47",
    flag: "🇸🇯",
    country: "Svalbard and Jan Mayen",
    iso2: "SJ",
  },
  { value: "+46", label: "+46", flag: "🇸🇪", country: "Sweden", iso2: "SE" },
  {
    value: "+41",
    label: "+41",
    flag: "🇨🇭",
    country: "Switzerland",
    iso2: "CH",
  },
  { value: "+963", label: "+963", flag: "🇸🇾", country: "Syria", iso2: "SY" },
  { value: "+886", label: "+886", flag: "🇹🇼", country: "Taiwan", iso2: "TW" },
  {
    value: "+992",
    label: "+992",
    flag: "🇹🇯",
    country: "Tajikistan",
    iso2: "TJ",
  },
  { value: "+255", label: "+255", flag: "🇹🇿", country: "Tanzania", iso2: "TZ" },
  { value: "+66", label: "+66", flag: "🇹🇭", country: "Thailand", iso2: "TH" },
  {
    value: "+670",
    label: "+670",
    flag: "🇹🇱",
    country: "Timor-Leste",
    iso2: "TL",
  },
  { value: "+228", label: "+228", flag: "🇹🇬", country: "Togo", iso2: "TG" },
  { value: "+690", label: "+690", flag: "🇹🇰", country: "Tokelau", iso2: "TK" },
  { value: "+676", label: "+676", flag: "🇹🇴", country: "Tonga", iso2: "TO" },
  {
    value: "+1868",
    label: "+1868",
    flag: "🇹🇹",
    country: "Trinidad and Tobago",
    iso2: "TT",
  },
  { value: "+216", label: "+216", flag: "🇹🇳", country: "Tunisia", iso2: "TN" },
  { value: "+90", label: "+90", flag: "🇹🇷", country: "Turkey", iso2: "TR" },
  {
    value: "+993",
    label: "+993",
    flag: "🇹🇲",
    country: "Turkmenistan",
    iso2: "TM",
  },
  {
    value: "+1649",
    label: "+1649",
    flag: "🇹🇨",
    country: "Turks and Caicos Islands",
    iso2: "TC",
  },
  { value: "+688", label: "+688", flag: "🇹🇻", country: "Tuvalu", iso2: "TV" },
  { value: "+256", label: "+256", flag: "🇺🇬", country: "Uganda", iso2: "UG" },
  { value: "+380", label: "+380", flag: "🇺🇦", country: "Ukraine", iso2: "UA" },
  {
    value: "+971",
    label: "+971",
    flag: "🇦🇪",
    country: "United Arab Emirates",
    iso2: "AE",
  },
  {
    value: "+44",
    label: "+44",
    flag: "🇬🇧",
    country: "United Kingdom",
    iso2: "GB",
  },
  {
    value: "+1",
    label: "+1",
    flag: "🇺🇸",
    country: "United States",
    iso2: "US",
  },
  { value: "+598", label: "+598", flag: "🇺🇾", country: "Uruguay", iso2: "UY" },
  {
    value: "+998",
    label: "+998",
    flag: "🇺🇿",
    country: "Uzbekistan",
    iso2: "UZ",
  },
  { value: "+678", label: "+678", flag: "🇻🇺", country: "Vanuatu", iso2: "VU" },
  {
    value: "+379",
    label: "+379",
    flag: "🇻🇦",
    country: "Vatican City",
    iso2: "VA",
  },
  { value: "+58", label: "+58", flag: "🇻🇪", country: "Venezuela", iso2: "VE" },
  { value: "+84", label: "+84", flag: "🇻🇳", country: "Vietnam", iso2: "VN" },
  {
    value: "+1284",
    label: "+1284",
    flag: "🇻🇬",
    country: "British Virgin Islands",
    iso2: "VG",
  },
  {
    value: "+1340",
    label: "+1340",
    flag: "🇻🇮",
    country: "US Virgin Islands",
    iso2: "VI",
  },
  {
    value: "+681",
    label: "+681",
    flag: "🇼🇫",
    country: "Wallis and Futuna",
    iso2: "WF",
  },
  {
    value: "+212",
    label: "+212",
    flag: "🇪🇭",
    country: "Western Sahara",
    iso2: "EH",
  },
  { value: "+967", label: "+967", flag: "🇾🇪", country: "Yemen", iso2: "YE" },
  { value: "+260", label: "+260", flag: "🇿🇲", country: "Zambia", iso2: "ZM" },
  { value: "+263", label: "+263", flag: "🇿🇼", country: "Zimbabwe", iso2: "ZW" },
] as const;

export default countryCodes;
